[build]
  command = ""
  # Publish from root directory where index.html is located
  # Alternative: use "dist" if Netlify expects dist folder
  publish = "."

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404