[build]
  # No build command needed for static HTML site
  command = ""
  
  # Publish the root directory (where index.html is located)
  publish = "."

# Static file headers
[[headers]]
  # Apply caching headers to static assets
  for = "/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Security headers for HTML pages
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for clean URLs and 404 handling
[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
