[build]
  # No build command needed for static HTML site
  command = ""
  
  # Publish the root directory (where index.html is located)
  publish = "."

[build.environment]
  # Disable yarn/npm dependency checks
  NODE_VERSION = "18"

[[headers]]
  # Apply caching headers to static assets
  for = "/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Security headers for HTML pages
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle client-side routing (if needed in the future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# 404 page redirect
[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
